using Microsoft.OpenApi.Models;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1",
        new OpenApiInfo
        {
            Title = "Swagger Weather Demo Documentation",
            Version = "v1",
            Description = "This is a demo to see how documentation can be generated by using Swagger + ReDoc.",
            Contact = new OpenApiContact
            {
                Name = "Nikolay Krondev",
                Email = "email@example.com"
            }
        });
});

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(options => options.SwaggerEndpoint("/swagger/v1/swagger.json", "Swagger Weather Demo Documentation v1"));
    
    app.UseReDoc(options => // adds default url to https://your-host-and-port/api-docs/
    {
        options.DocumentTitle = "Swagger Weather Demo Documentation";
        options.SpecUrl = "/swagger/v1/swagger.json";
    });
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();